version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/mathongo
      - REDIS_URL=redis://redis:6379
      - ADMIN_SECRET=${ADMIN_SECRET}
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - mathongo-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=mathongo
    restart: unless-stopped
    networks:
      - mathongo-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mathongo-network

volumes:
  mongo_data:
  redis_data:

networks:
  mathongo-network:
    driver: bridge
